[package]
name = "Ether"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
inkwell = { version = "0.7.0", features = ["llvm18-1"] }
either = "1.15.0"

[toolchain]
channel = "nightly"
